In [1]:
from sage.all import *
from mubs_utils import testMubs, testMubs2, saveMubs
import numpy as np

In [2]:
%reload_ext line_profiler
%reload_ext autoreload
%autoreload 2

Quick check for dimension for one qutrit.

In [3]:
F = GF(3, 'x')

mubs = [identity_matrix(3)]
for m in F:
    Bm = zero_matrix(SR, 3,3)
    for j, v in enumerate(F):
        for i, w in enumerate(F):
            pwr = ( (1/F(2))*w**2*m + v*w).trace()
            Bm[i,j] = exp(2*I*pi / 3)**Integer(lift(pwr)) * 1/sqrt(3)
    mubs.append(Bm)

In [4]:
for B in mubs:
    print(B)
    print('---')

[1 0 0]
[0 1 0]
[0 0 1]
---
[                        1/3*sqrt(3)                         1/3*sqrt(3)                         1/3*sqrt(3)]
[                        1/3*sqrt(3)       -1/6*sqrt(3)*(-I*sqrt(3) + 1) 1/3*sqrt(3)*(1/2*I*sqrt(3) - 1/2)^2]
[                        1/3*sqrt(3) 1/3*sqrt(3)*(1/2*I*sqrt(3) - 1/2)^2       -1/6*sqrt(3)*(-I*sqrt(3) + 1)]
---
[                        1/3*sqrt(3)                         1/3*sqrt(3)                         1/3*sqrt(3)]
[1/3*sqrt(3)*(1/2*I*sqrt(3) - 1/2)^2                         1/3*sqrt(3)       -1/6*sqrt(3)*(-I*sqrt(3) + 1)]
[1/3*sqrt(3)*(1/2*I*sqrt(3) - 1/2)^2       -1/6*sqrt(3)*(-I*sqrt(3) + 1)                         1/3*sqrt(3)]
---
[                        1/3*sqrt(3)                         1/3*sqrt(3)                         1/3*sqrt(3)]
[      -1/6*sqrt(3)*(-I*sqrt(3) + 1) 1/3*sqrt(3)*(1/2*I*sqrt(3) - 1/2)^2                         1/3*sqrt(3)]
[      -1/6*sqrt(3)*(-I*sqrt(3) + 1)                         1/3*sqrt(3) 1/3*sqrt(3)

In [5]:
testMubs2(mubs)

Testing set 0
Testing set 1
Testing set 2
Testing set 3


True

In [6]:
# saveMubs(mubs, 'MUBS/3-1-desarguesian')

Three qutrits example.

In [7]:
p = 3
n = 3
d = p**n

In [8]:
F = GF(d, 'x'); x = F.gen()
F

Finite Field in x of size 3^3

In [9]:
charpoly(x) # Conways poly again.

x^3 + 2*x + 1

In [10]:
F = [F(0)] + [x**j for j in range(26)]
F

[0,
 1,
 x,
 x^2,
 x + 2,
 x^2 + 2*x,
 2*x^2 + x + 2,
 x^2 + x + 1,
 x^2 + 2*x + 2,
 2*x^2 + 2,
 x + 1,
 x^2 + x,
 x^2 + x + 2,
 x^2 + 2,
 2,
 2*x,
 2*x^2,
 2*x + 1,
 2*x^2 + x,
 x^2 + 2*x + 1,
 2*x^2 + 2*x + 2,
 2*x^2 + x + 1,
 x^2 + 1,
 2*x + 2,
 2*x^2 + 2*x,
 2*x^2 + 2*x + 1,
 2*x^2 + 1]

Desarguesian spread.

In [11]:
two = F[1]+F[1]

In [15]:
mubs = [identity_matrix(d)]
for m in F:
    Bm = zero_matrix(SR, d,d)
    for j, v in enumerate(F):
        for i, w in enumerate(F):
            pwr = ( (1/two)*w*w*m + v*w).trace()
            Bm[i,j] = exp(2*I*pi / p)**Integer(pwr) * 1/sqrt(d)
    mubs.append(Bm)

In [16]:
testMubs2(mubs[15:21])

Testing set 0
Testing set 1
Testing set 2
Testing set 3
Testing set 4
Testing set 5


True

In [ ]:
# saveMubs(mubs, 'MUBS/3-3-desarguesian')
# (np.load('MUBS/3-3-desarguesian.npy')).shape

So the Desarguesian spread of course produces MUBs. Too large to check with sagemaths low speeds. Now unto Kantor spread given by Alberts twisted fields. The operation is given by:
$$w \circ m = mw^9 + m^3 w^3.$$

In [ ]:
mubs = [identity_matrix(d)]
for m in F:
    Bm = zero_matrix(SR, d,d)
    for j, v in enumerate(F):
        for i, w in enumerate(F):
            pwr = ((1/two)*w*(m*w**9 + m**3*w**3) + v*w).trace()
            Bm[i,j] = exp(2*I*pi / p)**Integer(lift(pwr)) * 1/sqrt(d)
    mubs.append(Bm)

In [ ]:
testMubs(mubs[10:12])

Good enough.

In [ ]:
saveMubs(mubs, 'MUBS/3-3-albert')
(np.load('MUBS/3-3-albert.npy')).shape