In [39]:
%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


In [40]:
import numpy as np
from sage.all import *
from mubs_utils import testMubs, saveMubs
reset()

In [41]:
p = 2
n = 2
q = p**n

# GR(4,2)
R  = PolynomialRing(Integers(4), 't'); t = R.gen()
GR = R.quotient(t**2+t+1, 'w'); w = GR.gen()
GR

Univariate Quotient Polynomial Ring in w over Ring of integers modulo 4 with modulus t^2 + t + 1

In [42]:
GR.cardinality()

16

In [43]:
list(GR)

[0,
 1,
 2,
 3,
 w,
 w + 1,
 w + 2,
 w + 3,
 2*w,
 2*w + 1,
 2*w + 2,
 2*w + 3,
 3*w,
 3*w + 1,
 3*w + 2,
 3*w + 3]

In [44]:
# def generalizedFrobenius(a, b):
#     return a**2 + GR(2)*b**2

def ringTrace(a, b):
    s = GR(0)
    for k in range(n):
        s += a**(2**k) + GR(2)*b**(2**k)
    return s 

for a in GR:
    for b in GR:
        if not ringTrace(a, b) == a + GR(2)*b + a**2 + GR(2)*b**2:
            raise Error('Trace not well defined!')
print('Trace defined!')

Trace defined!


In this case the ring generator $w$ coincides with the $\xi$.

In [45]:
w**3

1

In [46]:
T = [0] + [w**k for k in range((2**n - 2) + 1)]
T

[0, 1, w, 3*w + 3]

In [47]:
def brute2adic(x):
    for a in T:
        for b in T:
            if x == a + GR(2)*b:
                return (a,b)

In [48]:
mubs = [identity_matrix(q)]
for m in T:
    Bm = zero_matrix(SR, q, q)
    for j, v in enumerate(T):
        for i, w in enumerate(T):
            a, b = brute2adic(w**2 * m + 2 * w * v)
            pwr  = Integer(lift(ringTrace(a, b)))
            Bm[i,j] = 1/sqrt(q) * I**pwr
    mubs.append(Bm)

In [49]:
for i, m in enumerate(T):
    print(m)
    print(mubs[i+1]*2)
    print('\n')

0
[ 1  1  1  1]
[ 1  1 -1 -1]
[ 1 -1 -1  1]
[ 1 -1  1 -1]


1
[ 1  1  1  1]
[-1 -1  1  1]
[-I  I  I -I]
[-I  I -I  I]


w
[ 1  1  1  1]
[-I -I  I  I]
[-1  1  1 -1]
[-I  I -I  I]


3*w + 3
[ 1  1  1  1]
[-I -I  I  I]
[-I  I  I -I]
[-1  1 -1  1]




In [50]:
from mubs_utils import saveMubs
saveMubs(mubs, 'MUBS/2-2-desarguesian')

Saved to MUBS/2-2-desarguesian


In [51]:
def testMubs(mubs):
    for B in mubs:
        for V in mubs:
            if B != V:
                for j in range(4):
                    for k in range(4):
                        r = (transpose(B[:,j]) * V[:,k]).norm().abs()**2
                        if r != 1/4:
                            print(r)
                            raise Exception('Not MUBs!')
    return True

In [52]:
testMubs(mubs)

True

---
Now for five qubits, $\mathcal H = \mathbb C^{2^5}$.

In [53]:
p = 2
n = 5
q = p**n

In [54]:
F = GF(2**5, 'w', repr='poly'); w = F.gen()
F

Finite Field in w of size 2^5

In [55]:
charpoly(w) # defaults to Conway polynomial

x^5 + x^2 + 1

In [56]:
# GR(4,5)
R  = PolynomialRing(Integers(4), 't'); t = R.gen()

In [57]:
factor(t**5 + t**2 + 1)

t^5 + t^2 + 1

In [58]:
GR = R.quotient(t**5 + t**2 + 1, 'alpha'); alpha = GR.gen()
GR

Univariate Quotient Polynomial Ring in alpha over Ring of integers modulo 4 with modulus t^5 + t^2 + 1

In [59]:
alpha**5 + alpha**2 + 1

0

Ring generator $\alpha$ is not the multiplicative generator of the Teichmüller set as can be seen below:

In [60]:
alpha**(2**5-1)

2*alpha^3 + 2*alpha + 1

Andrés found the $2^5-1$-th primitive root of unity though:

In [61]:
xi = alpha**2 + 2*alpha + 1
xi**(2**5-1)

1

In [62]:
T = [GR(0)] + [xi**k for k in range(2**n - 2 + 1)]
len(T)

32

In [63]:
T[-1]*xi

1

In [64]:
T # coincides with Andre's MAGMA code.

[0,
 1,
 alpha^2 + 2*alpha + 1,
 alpha^4 + 2*alpha^2 + 1,
 3*alpha^4 + 3*alpha^3 + alpha^2 + alpha + 3,
 2*alpha^4 + 3*alpha^3 + alpha^2 + 2,
 alpha^4 + 3*alpha^3 + 2*alpha + 3,
 3*alpha^4 + 2*alpha^2 + 3*alpha + 2,
 alpha^4,
 alpha^4 + 3*alpha^3 + 2*alpha^2 + 3*alpha + 2,
 alpha^4 + alpha^3 + alpha^2 + 2*alpha + 1,
 3*alpha^2 + 3*alpha + 2,
 3*alpha^4 + alpha^3 + 3*alpha^2 + 3*alpha + 2,
 3*alpha^3 + 3,
 2*alpha^4 + 3*alpha^3 + 2*alpha,
 3*alpha^3 + alpha^2 + 1,
 3*alpha^4 + alpha^3 + 3*alpha^2 + 2*alpha + 2,
 2*alpha^3 + 2*alpha^2 + 3*alpha + 3,
 2*alpha^4 + alpha^3 + alpha^2 + alpha + 1,
 alpha^4 + 2*alpha^3 + 3*alpha^2 + alpha,
 alpha^2,
 alpha^4 + 2*alpha^3 + alpha^2,
 2*alpha^4 + 3*alpha^3 + alpha^2 + 3*alpha,
 alpha^4 + 2*alpha^3 + alpha + 1,
 alpha^4 + 2*alpha^3 + 3*alpha^2 + 2*alpha + 1,
 alpha^3 + 3*alpha + 1,
 2*alpha^4 + 2*alpha^2 + alpha,
 3*alpha^3 + 3*alpha,
 2*alpha^4 + 2*alpha^3 + 3*alpha^2 + 3*alpha + 1,
 alpha^4 + alpha^3 + 3*alpha + 3,
 3*alpha^4 + 3*alpha^3 + 2*alp

In [65]:
xi

alpha^2 + 2*alpha + 1

In [66]:
def ringTrace(a, b):
    s = GR(0)
    for k in range(n):
        s += a**(2**k) + GR(2)*b**(2**k)
    return s 

In [67]:
def brute2adic(x):
    for a in T:
        for b in T:
            if x == a + GR(2)*b:
                return (a,b)

In [68]:
def dumb2adic(x):
    for b in T:
        a = x - GR(2)*b
        if a in T:
            return (a,b)

Kantor mubs.

In [69]:
def createMubs(k=None):
    mubs = [identity_matrix(q)]
    for m in T[:k]:
        Bm = zero_matrix(SR, q, q)
        for j, v in enumerate(T):
            for i, w in enumerate(T):
                wom = m**2*w + m*ringTrace(w, 0) + ringTrace(m*w, 0)
                a, b = dumb2adic(w * wom + GR(2) * w * v)
                pwr  = Integer(lift(ringTrace(a, b)))
                Bm[i,j] = 1/sqrt(q) * I**pwr
        mubs.append(Bm)
    return mubs

In [23]:
%lprun -f createMubs createMubs(k=2)

Timer unit: 1e-09 s

Total time: 6.39752 s
File: /var/folders/33/k06yq9x95jqcnbk_bh41j4qc0000gn/T/ipykernel_26513/2185357466.py
Function: createMubs at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def createMubs(k=None):
     2         1    2182000.0 2182000.0      0.0      mubs = [identity_matrix(q)]
     3         2       5000.0   2500.0      0.0      for m in T[:k]:
     4         2   18502000.0 9251000.0      0.3          Bm = zero_matrix(SR, q, q)
     5        64      74000.0   1156.2      0.0          for j, v in enumerate(T):
     6      2048    3646000.0   1780.3      0.1              for i, w in enumerate(T):
     7      2048 2301636000.0 1123845.7     36.0                  wom = m**2*w + m*ringTrace(w, 0) + ringTrace(m*w, 0)
     8      2048 2338481000.0 1141836.4     36.6                  a, b = dumb2adic(w * wom + GR(2) * w * v)
     9      2048 1191788000.0 581927.7     18.6                  pwr  =

In [70]:
mubs = createMubs()

In [76]:
from mubs_utils import saveMubs
import numpy as np

In [74]:
saveMubs(mubs, 'MUBS/2-5-kantor')

Saved to MUBS/2-5-kantor


In [77]:
M = np.load('MUBS/2-5-kantor.npy')
M.shape

(1056, 32)

In [89]:
1/32

0.03125

In [104]:
k = 8
np.round(np.abs(M[64:96,29] @ M[32*k:32*(k+1),15])**2, 5)

0.03125

Desarguesian spread.

In [105]:
def createMubs(k=None):
    mubs = [identity_matrix(q)]
    for m in T[:k]:
        Bm = zero_matrix(SR, q, q)
        for j, v in enumerate(T):
            for i, w in enumerate(T):
                a, b = dumb2adic(w**2 * m + 2 * w * v)
                pwr  = Integer(lift(ringTrace(a, b)))
                Bm[i,j] = 1/sqrt(q) * I**pwr
        mubs.append(Bm)
    return mubs

In [106]:
mubs = createMubs()

In [109]:
saveMubs(mubs, 'MUBS/2-5-desarguesian')

Saved to MUBS/2-5-desarguesian


In [111]:
M = np.load('MUBS/2-5-desarguesian.npy')
M.shape

(1056, 32)

In [114]:
k = 12
np.round(np.abs(M[64:96,29] @ M[32*k:32*(k+1),0])**2, 5)

0.03125