In [1]:
from sage.all import *
import numpy as np

We will quickly investigate some of the properties of the Weyl-Heisenberg group.

In [9]:
p = 2
n = 1
d = p**n

In [10]:
def getXZ(d):
    omega = exp(2*pi*I / d)
    
    X = Permutation(list(range(2,d+1)) + [1]).to_matrix()
    Z = diagonal_matrix(SR, [omega**j for j in range(d)])

    return X, Z

In [11]:
X, Z = getXZ(2)

It is true that $X^p = Z^p = 1$.

In [12]:
X**p == identity_matrix(d) and (Z**p) == identity_matrix(d)

True

In [24]:
def D(a,b):
    return X**a * Z**b

In [25]:
for a in range(d):
    for b in range(d):
        if D(a,b)**(p) != identity_matrix(d):
            print(D(a,b))
            raise Exception('Not full group')
print('Full group')

[1 0 0]
[0 1 0]
[0 0 1]


Exception: Not full group

In [15]:
((X*Z)**p).apply_map(lambda x: x.full_simplify())

[-1  0]
[ 0 -1]

In [16]:
X.det()

-1

In [17]:
Z.det().full_simplify()

-1

In [20]:
X, Z = getXZ(3)
X

[0 0 1]
[1 0 0]
[0 1 0]

In [45]:
F = GF(3**2, 'x')
x = F.gen();
F = [F(0)] + [x**j for j in range(8)]
F

[0, 1, x, x + 1, 2*x + 1, 2, 2*x, 2*x + 2, x + 2]

In [54]:
charpoly(x)

x^2 + 2*x + 2

Let the field basis be $(1,x)$ and let the standard basis be indexed by the field.

In [48]:
omega = exp(2*pi*I / 3)

In [52]:
diagonal_matrix(omega**(n.trace()) for n in F).apply_map(lambda t: t.full_simplify())

[                   1                    0                    0                    0                    0                    0                    0                    0                    0]
[                   0 -1/2*I*sqrt(3) - 1/2                    0                    0                    0                    0                    0                    0                    0]
[                   0                    0  1/2*I*sqrt(3) - 1/2                    0                    0                    0                    0                    0                    0]
[                   0                    0                    0                    1                    0                    0                    0                    0                    0]
[                   0                    0                    0                    0  1/2*I*sqrt(3) - 1/2                    0                    0                    0                    0]
[                   0                    0   